# Generated by Django 4.2.3 on 2023-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0002_alter_event_address_alter_event_category_and_more")]

    operations = [
        migrations.AlterField(
            model_name="event", name="end_date", field=models.DateTimeField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
