# Generated by Django 4.2.3 on 2023-07-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
