# Generated by Django 4.2.3 on 2023-07-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RenameModel('Categories', 'Category')
    ]
