# Generated by Django 4.2.3 on 2023-07-22 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_alter_category_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ratings',
            field=models.ManyToManyField(blank=True, through='events.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
