# Generated by Django 4.2.3 on 2023-07-22 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_alter_event_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ratings',
            field=models.ManyToManyField(through='events.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.SmallIntegerField(),
        ),
    ]
