# Generated by Django 4.2.3 on 2023-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0013_remove_event_place_event_type_alter_event_address")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="current_participants_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="event",
            name="desired_participants_number",
            field=models.IntegerField(default=1),
        ),
    ]
