# Generated by Django 4.2.3 on 2023-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0014_event_current_participants_number_and_more")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="current_participants_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="event",
            name="desired_participants_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
