# Generated by Django 4.2.3 on 2023-07-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("events", "0015_alter_event_current_participants_number_and_more")]

    operations = [
        migrations.RemoveField(model_name="event", name="place"),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("open", "Open"), ("private", "Private")], default="open", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, default="Minsk", max_length=250, null=True),
        ),
    ]
