# Generated by Django 4.2.3 on 2023-07-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['value'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='value',
        ),
    ]
