# Generated by Django 4.2.3 on 2023-11-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_event_place_event_type_alter_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
