# Generated by Django 4.2.3 on 2023-11-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_url_field_instead_of_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_url',
        ),
    ]
