# Generated by Django 4.2.3 on 2023-12-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_url_field_instead_of_image_field_squashed_0019_imagedields_to_charfields")
    ]

    operations = [migrations.RemoveField(model_name="event", name="current_participants_number")]
