# Generated by Django 4.2.3 on 2024-02-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0014_city_user_city"), ("events", "0022_review")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to="profiles.city"
            ),
        )
    ]
