# Generated by Django 4.2.3 on 2024-03-05 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0024_alter_event_city")]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="events.rating",
            ),
        )
    ]
