# Generated by Django 4.2.3 on 2024-03-23 07:23

import apps.events.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(choices=[(840, apps.events.utils.Currency['USD']), (978, apps.events.utils.Currency['EUR']), (643, apps.events.utils.Currency['RUB']), (974, apps.events.utils.Currency['BYN'])], default=apps.events.utils.Currency['BYN']),
        ),
        migrations.AddField(
            model_name='event',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=250, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='participants_age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='event',
            name='repeatability',
            field=models.CharField(choices=[('Daily', apps.events.utils.PeriodRepeatability['DAY']), ('Weekly', apps.events.utils.PeriodRepeatability['WEEK']), ('Monthly', apps.events.utils.PeriodRepeatability['MONTH'])], default=apps.events.utils.PeriodRepeatability['MONTH']),
        ),
        migrations.AddField(
            model_name='event',
            name='repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
