# Generated by Django 4.2.3 on 2024-03-30 17:54

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "events",
            "0027_event_end_time_event_start_time_and_more_squashed_0028_event_private_url",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="any_participant_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="city_north_east_point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(27.561831, 53.902284), srid=4326
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="city_south_west_point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(27.561831, 53.902284), srid=4326
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(default="Беларусь", max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True, default="Беларусь, Минск", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event", name="city", field=models.CharField(default="Минск", max_length=50)
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=3, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.RemoveField(model_name="event", name="currency"),
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.currency",
            ),
        ),
    ]
