# Generated by Django 4.2.3 on 2024-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_any_participant_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='Беларусь, Минск', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='desired_participants_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
