# Generated by Django 5.0.4 on 2024-04-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_remove_event_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='event_ratings', to='events.rating'),
        ),
    ]
