# Generated by Django 4.2.3 on 2024-04-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('events', '0035_event_chat'), ('events', '0036_alter_event_chat')]

    dependencies = [
        ('websockets', '0005_remove_message_sender_remove_notification_sender_and_more'),
        ('websockets', '0001_initial'),
        ('events', '0034_rename_private_url_event_private_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_event', to='websockets.chat', verbose_name='Chat'),
        ),
    ]
