# Generated by Django 4.2.3 on 2024-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_rename_private_url_event_private_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='response',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
