# Generated by Django 4.2.3 on 2024-05-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('events', '0034_rename_private_url_event_private_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chat',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_event', to='chats.chat', verbose_name='Chat'),
        ),
    ]
