# Generated by Django 4.2.3 on 2024-05-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_event_chat'),
        ('events', '0036_category_image_url'),
    ]

    operations = [
    ]
