# Generated by Django 4.2.3 on 2024-06-14 18:28

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_remove_event_city_north_east_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(27.561831, 53.902284), srid=4326),
        ),
    ]
