# Generated by Django 4.2.3 on 2024-08-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_remove_event_city_location_alter_event_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
