# Generated by Django 4.2.3 on 2024-09-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "__first__"), ("events", "0041_remove_event_country")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.city"
            ),
        )
    ]
