# Generated by Django 4.2.3 on 2024-09-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0042_alter_event_city")]

    operations = [migrations.RemoveField(model_name="event", name="city")]
