# Generated by Django 4.2.3 on 2024-09-24 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0045_invitation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="invitation", unique_together=set()),
        migrations.RemoveField(model_name="invitation", name="recipient"),
        migrations.AddField(
            model_name="invitation",
            name="recipient",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="list_of_recipients"
            ),
        ),
    ]
