# Generated by Django 4.2.3 on 2023-11-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_url_field_instead_of_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatar_url',
        ),
    ]
