# Generated by Django 4.2.3 on 2023-07-30 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0002_user_avatar")]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"verbose_name": "User", "verbose_name_plural": "Users"}
        )
    ]
