# Generated by Django 4.2.3 on 2023-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_url_field_instead_of_image_field_squashed_0006_imagedields_to_charfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
