# Generated by Django 4.2.3 on 2024-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0008_rename_avatar_url_user_image_url")]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.EmailField(max_length=255, unique=True)
        ),
        migrations.AlterField(
            model_name="user", name="username", field=models.CharField(max_length=128)
        ),
    ]
