# Generated by Django 4.2.3 on 2024-01-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userrating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='user_rater',
        ),
    ]
