# Generated by Django 4.2.3 on 2023-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
