# Generated by Django 4.2.3 on 2023-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<<< HEAD:apps/profiles/migrations/0011_alter_userrating_value.py
        ('profiles', '0010_userrating'),
========
        ('profiles', '0009_userrating'),
>>>>>>>> origin/feature/8693ketzk-Add-location-entity:apps/profiles/migrations/0010_alter_userrating_value.py
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='value',
            field=models.SmallIntegerField(null=True),
        ),
    ]