# Generated by Django 4.2.3 on 2024-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0012_user_age_user_bio")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, unique=False),
        )
    ]
