# Generated by Django 4.2.3 on 2024-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONE', 'None')], default='NONE', max_length=15, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=15, verbose_name='Type'),
        ),
    ]
