# Generated by Django 4.2.3 on 2024-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0020_user_gender_user_type")]

    operations = [migrations.RemoveField(model_name="user", name="age")]
