# Generated by Django 4.2.3 on 2024-06-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0039_remove_event_city_north_east_point_and_more"),
        ("profiles", "0021_remove_user_age"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="city"),
        migrations.AddField(
            model_name="user",
            name="city_location",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="events.city"
            ),
        ),
    ]
