# Generated by Django 4.2.3 on 2024-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='CityLocation',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='CityLocation',
            name='place_id',
        ),
    ]
