# Generated by Django 4.2.3 on 2024-06-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_citylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylocation',
            name='place_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='citylocation',
            constraint=models.UniqueConstraint(fields=('place_id', 'location'), name='unique_location'),
        ),
    ]
