# Generated by Django 4.2.3 on 2024-06-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_citylocation_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocation',
            name='place_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
