# Generated by Django 4.2.3 on 2024-06-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_user_city_user_city_location'),
        ('profiles', '0023_remove_user_email_notifications_allowed_and_more'),
    ]

    operations = [
    ]
