# Generated by Django 4.2.3 on 2024-05-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_remove_city_city_name_remove_city_place_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citylocation',
            table='city_location',
        ),
    ]
