# Generated by Django 4.2.3 on 2024-08-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('profiles', '0024_merge_20240616_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city_location',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city'),
        ),
    ]
