# Generated by Django 4.2.3 on 2024-05-31 09:31

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_citylocation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(27.561831, 53.902284), srid=4326, unique=True),
        ),
    ]
