# Generated by Django 4.2.3 on 2024-09-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0025_remove_user_city_location_user_city")]

    operations = [migrations.RemoveField(model_name="user", name="city")]
