version: '3'
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ../db/Dockerfile
    restart: always
    env_file:
      - ../.env
    ports:
      - "5555:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database_volume:
