FOLLOW_URL = "profiles:Followers-follow_user"
ACCEPT_URL = "profiles:Followers-accept_follow_request"
UNFOLLOW_URL = "profiles:Followers-unfollow_user"
LIST_FOLLOWERS_URL = "profiles:Followers-list_user_followers"
LIST_FOLLOWING_URL = "profiles:Followers-list_user_following"
UPDATE_URL = "profiles:Profiles-detail"
