app = "meetups-dev"
primary_region = "waw"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]
  builtin = "python"

[build.args]
  BP_CPYTHON_VERSION = "3.11.4"

[build.settings]
  pythonbase = "3.11-slim-buster"