# Generated by Django 4.2.3 on 2023-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_renamed_image_and_avatar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
