# Generated by Django 4.2.3 on 2024-04-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('websockets', '0001_initial'), ('websockets', '0002_remove_chat_messages'), ('websockets', '0003_alter_chat_participants'), ('websockets', '0004_alter_chat_participants'), ('websockets', '0005_remove_message_sender_remove_notification_sender_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EVENT', 'Event'), ('DIRECT', 'Direct')], max_length=15, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_participants', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=528, verbose_name='Message text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='websockets.chat', verbose_name='Chat')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FOLLOW', 'Follow'), ('FOLLOW_REQUEST', 'Follow Request'), ('ACCEPT', 'Accept')], max_length=20, verbose_name='Type')),
                ('additional_data', models.JSONField(blank=True, default=None, help_text='Unique data for certain type of notification', null=True, verbose_name='Additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['created_at'],
            },
        ),
    ]
