# Generated by Django 4.2.3 on 2024-04-29 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0001_squashed_0005_remove_message_sender_remove_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
