# Generated by Django 4.2.3 on 2023-07-08 09:54

from django.contrib.auth.models import Group, Permission, User
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from apps.events.models.events import Event


def forwards_func(apps, schema_editor):
    regular_group, created = Group.objects.get_or_create(name="Regular")
    event_maker_group, created = Group.objects.get_or_create(name="Event_maker")

    content_type = ContentType.objects.get_for_model(Event)
    event_permission = Permission.objects.filter(content_type=content_type)

    for perm in event_permission:
        if "view" in perm.codename:
            event_maker_group.permissions.add(perm)
            regular_group.permissions.add(perm)
        else:
            event_maker_group.permissions.add(perm)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("events", "0001_initial")]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
