# Generated by Django 4.2.3 on 2024-05-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(choices=[('FOLLOW', 'Follow'), ('FOLLOW_REQUEST', 'Follow Request'), ('ACCEPT', 'Accept')], max_length=20, verbose_name='Type')),
                ('additional_data', models.JSONField(blank=True, default=None, help_text='Unique data for certain type of notification', null=True, verbose_name='Additional data')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['created_at'],
            },
        ),
    ]
