# Generated by Django 4.2.3 on 2024-05-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('notifications', '0001_initial'), ('notifications', '0002_notification_updated_at_notification_updated_by_and_more'), ('notifications', '0003_alter_notification_type')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(choices=[('NEW_FOLLOWER', 'New Follower'), ('NEW_FOLLOW_REQUEST', 'New Follow Request'), ('ACCEPTED_FOLLOW_REQUEST', 'Accepted Follow Request')], max_length=50, verbose_name='Type')),
                ('additional_data', models.JSONField(blank=True, default=None, help_text='Unique data for certain type of notification', null=True, verbose_name='Additional data')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['created_at'],
            },
        ),
    ]
