# Generated by Django 4.2.3 on 2024-05-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_updated_at_notification_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_FOLLOWER', 'New Follower'), ('NEW_FOLLOW_REQUEST', 'New Follow Request'), ('ACCEPTED_FOLLOW_REQUEST', 'Accepted Follow Request')], max_length=50, verbose_name='Type'),
        ),
    ]
