# Generated by Django 4.2.3 on 2024-06-16 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('notifications', '0005_alter_notification_type_and_more'), ('notifications', '0006_alter_emailnotificationspreferences_user_and_more'), ('notifications', '0007_alter_emailnotificationspreferences_options_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('new_message', 'New Message'), ('new_follower', 'New Follower'), ('new_follow_request', 'New Follow Request'), ('accepted_follow_request', 'Accepted Follow Request'), ('event_start', 'Event Start'), ('new_invite_to_event', 'New Invite To Event'), ('new_interesting_event_near', 'New Interesting Event Near'), ('new_following_user_event', 'New Following User Event'), ('following_user_near_going_to_event', 'Following User Near Going To Event')], max_length=50, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='EmailNotificationsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.BooleanField(default=True)),
                ('event_start', models.BooleanField(default=True)),
                ('new_invite_to_event', models.BooleanField(default=True)),
                ('new_interesting_event_near', models.BooleanField(default=True)),
                ('new_following_user_event', models.BooleanField(default=True)),
                ('following_user_near_going_to_event', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': 'email_notifications_preferences',
            },
        ),
        migrations.CreateModel(
            name='InAppNotificationsPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.BooleanField(default=True)),
                ('event_start', models.BooleanField(default=True)),
                ('new_invite_to_event', models.BooleanField(default=True)),
                ('new_interesting_event_near', models.BooleanField(default=True)),
                ('new_following_user_event', models.BooleanField(default=True)),
                ('following_user_near_going_to_event', models.BooleanField(default=True)),
                ('new_message', models.BooleanField(default=True)),
                ('new_follower', models.BooleanField(default=True)),
                ('new_follow_request', models.BooleanField(default=True)),
                ('accepted_follow_request', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_related_name': 'in_app_notifications_preferences',
            },
        ),
    ]
