# Generated by Django 4.2.3 on 2024-10-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0009_notification_status")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("new_message", "New Message"),
                    ("new_follower", "New Follower"),
                    ("new_follow_request", "New Follow Request"),
                    ("accepted_follow_request", "Accepted Follow Request"),
                    ("event_start", "Event Start"),
                    ("new_invite_to_event", "New Invite To Event"),
                    ("new_interesting_event_near", "New Interesting Event Near"),
                    ("invitation to event accepted", "Invite To Event Accepted"),
                    ("invitation to event rejected", "Invite To Event Rejected"),
                    ("new_following_user_event", "New Following User Event"),
                    ("following_user_near_going_to_event", "Following User Near Going To Event"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        )
    ]
